/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LifestoryRouteImport } from './routes/lifestory'
import { Route as KarakterRouteImport } from './routes/karakter'
import { Route as DedektifRouteImport } from './routes/dedektif'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LifestoryRoute = LifestoryRouteImport.update({
  id: '/lifestory',
  path: '/lifestory',
  getParentRoute: () => rootRouteImport,
} as any)
const KarakterRoute = KarakterRouteImport.update({
  id: '/karakter',
  path: '/karakter',
  getParentRoute: () => rootRouteImport,
} as any)
const DedektifRoute = DedektifRouteImport.update({
  id: '/dedektif',
  path: '/dedektif',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dedektif': typeof DedektifRoute
  '/karakter': typeof KarakterRoute
  '/lifestory': typeof LifestoryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dedektif': typeof DedektifRoute
  '/karakter': typeof KarakterRoute
  '/lifestory': typeof LifestoryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dedektif': typeof DedektifRoute
  '/karakter': typeof KarakterRoute
  '/lifestory': typeof LifestoryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dedektif' | '/karakter' | '/lifestory' | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dedektif' | '/karakter' | '/lifestory' | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/dedektif'
    | '/karakter'
    | '/lifestory'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DedektifRoute: typeof DedektifRoute
  KarakterRoute: typeof KarakterRoute
  LifestoryRoute: typeof LifestoryRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifestory': {
      id: '/lifestory'
      path: '/lifestory'
      fullPath: '/lifestory'
      preLoaderRoute: typeof LifestoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karakter': {
      id: '/karakter'
      path: '/karakter'
      fullPath: '/karakter'
      preLoaderRoute: typeof KarakterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dedektif': {
      id: '/dedektif'
      path: '/dedektif'
      fullPath: '/dedektif'
      preLoaderRoute: typeof DedektifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DedektifRoute: DedektifRoute,
  KarakterRoute: KarakterRoute,
  LifestoryRoute: LifestoryRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
